# Generated by Django 4.0.1 on 2022-01-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='書籍名', max_length=30)),
                ('author', models.CharField(help_text='著者名', max_length=30)),
                ('yomigana', models.CharField(help_text='読み仮名', max_length=30)),
                ('company', models.CharField(help_text='出版社', max_length=30)),
                ('date', models.DateField(help_text='出版日')),
                ('page', models.IntegerField(help_text='ページ数')),
                ('chance', models.CharField(help_text='購入のきっかけ', max_length=100)),
                ('overview', models.TextField(help_text='概要')),
            ],
        ),
    ]
